meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: elpaaso_sandbox_leader_z1
    templates:
    - name: elpaaso-sandbox
      release: elpaaso-sandbox
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    properties: {}
  - name: elpaaso_sandbox_z1
    templates:
    - name: elpaaso-sandbox
      release: elpaaso-sandbox
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      elpaaso_sandbox:
        leader_address: (( merge ))

networks: (( merge ))

properties: {}
